title: Frame 9!
email: your-email@example.com
description: >- 
  A simple multipurpose 9 frame gallery theme for jekyll
tagline: >-
  The 9 frame gallery theme for jekyll
baseurl: ""
url: "frame9.codekarma.com"

twitter:
  username: codekarmadev
  card: summary

twitter_username: codekarmadev
github_username: CodeKarmaDev

theme: frame9-jekyll-theme

frame9:
  show_current_tab: false
  avatar: 'assets/img/avatar.png'
  footer_links:
    - title: Github
      url: 'https://github.com/CodeKarmaDev/frame9-jekyll-theme'


plugins:
  - jekyll-feed
  - jekyll-seo-tag


sass:
  load_paths:
    - _sass
    - node_modules
  style: compressed


collections:
  tabs:
    sort_by: order
    output: true
    permalink: /:name/
  sections:
    output: false

defaults:  
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      show_sibling_nav: true
  - scope:
      path: ''
      type: tabs
    values:
      layout: default

  - scope:
      path: ''
      type: section
    values:
      layout: section

exclude:
  - graphics
  - .gitignore
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package-lock.json
  - package.json
  - frame9-jekyll-theme.gemspec
  - lib

